//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicProductUpdate
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int productId { get; set; }
        [Required]
        public string productName { get; set; }

        [Required]
        public string productDescription { get; set; }

        [Required]
        public Nullable<int> productPrice { get; set; }
        public string productImage { get; set; }

        [Required]
        public Nullable<int> categoryId { get; set; }

        public virtual Category Category { get; set; }
    }
}
